#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
    printf "%s\n" "This script must be run as root.."
    exit 1
fi


repro=(
"clamav"
"clamav-daemon"
"clamav-freshclam"
"clamdscan"
"clamfs"
"debsums"
"extrepo"
"fonts-noto-color-emoji"
"gimp"
"glow"
"gomuks"
"hunspell-de-de"
"keepassxc"
"libosinfo-bin"
"libreoffice-l10n-de"
"libvirt-daemon-system"
"mat2"
"mythes-de"
"needrestart"
"net-tools"
"nethogs"
"nheko"
"nmap"
"osinfo-db-tools"
"ovmf"
"proton-vpn-cli"
"protonvpn-stable-release"
"qemu-system"
"qemu-system-gui"
"qemu-system-modules-spice"
"qemu-utils"
"qrencode"
"quickjs"
"shellcheck"
"spice-client-gtk"
"swtpm"
"sysstat"
"ventoy-bin"
"virt-manager"
"virt-viewer"
"virtinst"
"wireshark"
"yt-dlp"
"zbar-tools"
)

if ! command -v nala > /dev/null; then
	nala update
	nala upgrade
	nala install "${repro[@]}"
elif command -v apt > /dev/null; then
	apt update
	apt install
	apt install "${repro[@]}"
else
	exit 1
fi


printf "%s\n" "Installation from repro completed"


