#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
    printf "%s\n" "This script must be run as root.."
    exit 1
fi

userid="1000"
username="$( grep "$userid" /etc/passwd  )"
username="${username%%:*}"

#------------ delete user from sudo -----------------------------------#

gpasswd -d "$username" sudo

#------------ set sudo permissions for users --------------------------#

printf "%s\n" "%users ALL=(root) PASSWD: $( command -v nethogs ) *" > /etc/sudoers.d/nethogs \
&& chmod 440 /etc/sudoers.d/nethogs


nmap_path="$(command -v nmap)"
cat > /etc/sudoers.d/nmap <<EOF
Cmnd_Alias NMAP_COMMON = \
    $nmap_path ^(((-sL|-sn|-sS|-sT|-sU|-O|-Pn|-n|-F|-v{1,3}|--open|--reason|--traceroute|-T[0-5]|--osscan-limit|--osscan-guess|-p-|-p [0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*|--top-ports [1-9][0-9]{0,4}|-o(N|X|G) -)) )*((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(/([0-9]|[12][0-9]|3[0-2]))?( ((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(/([0-9]|[12][0-9]|3[0-2]))?)*$, \
    $nmap_path ^--datadir /usr/share/nmap -sV (((-sS|-sT|-sU|-O|-Pn|-n|-F|-v{1,3}|--open|--reason|--traceroute|-T[0-5]|--version-light|--version-all|--osscan-limit|--osscan-guess|-p-|-p [0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*|--top-ports [1-9][0-9]{0,4}|-o(N|X|G) -)) )*((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(/([0-9]|[12][0-9]|3[0-2]))?( ((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(/([0-9]|[12][0-9]|3[0-2]))?)*$
S
%users ALL=(root) PASSWD: NOSETENV: NMAP_COMMON
EOF
chmod 440 /etc/sudoers.d/nethogs


systemctl_path="$(command -v systemctl)" || exit 1
cat > /etc/sudoers.d/service-restarts <<EOF
Cmnd_Alias SERVICE_RESTARTS = \
    $systemctl_path restart clamav-daemon.service, \
    $systemctl_path restart NetworkManager.service, \
    $systemctl_path restart libvirtd.service

%users ALL=(root) PASSWD: SERVICE_RESTARTS
EOF
chmod 440 /etc/sudoers.d/service-restarts

#----------------------------------------------------------------------#
