#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
    printf "%s\n" "This script must be run as root.."
    exit 1
fi

UpdateRepo(){
	if command -v nala > /dev/null; then
		nala update && nala upgrade
	elif command -v apt > /dev/null ; then
		apt update && apt upgrade
	else
		exit 1
	fi
}


InstallApp(){
	local apps=("$@")
	if command -v nala > /dev/null; then
		nala install "${apps[@]}"
	elif command -v apt > /dev/null; then
		apt install "${apps[@]}"
	else
		exit 1
	fi
}

InstallProtonVPN(){
	wget https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.8_all.deb
	dpkg -i ./protonvpn-stable-release_1.0.8_all.deb && UpdateRepo
	InstallApp proton-vpn-cli
}

InstallLibreWolf(){
	InstallApp extrepo -y
	extrepo enable librewolf && extrepo update librewolf
	UpdateRepo && InstallApp librewolf -y
}


main(){
	local c=0
	InstallProtonVPN || (( c++ ))
	InstallLibreWolf || (( c++ ))
	if (( c == 0 )); then
		printf "%s\n" "Installation from external repos complete"
	else
		exit 1
	fi
}

main

