#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
    printf "%s\n" "This script must be run as root.."
    exit 1
fi

#----------------------------------------------------------------------#

Help(){
	cat << 'EOF'
Set predefined rights for any user. Without given user the
default is UID 1000.

-h | --help			show this help
-u [USERID]			userid to set rights
-n [USERNAME]		username to set rights
EOF
}


ParseCommandLineOptions(){
	local cli_options=("$@")
	options=$(getopt -o hu:n: --long help -- "${cli_options[@]}")
	eval set -- "$options"
	while true; do
		case "$1" in
			-h|--help) Help; exit 0;;
			-u) P_uid="$2"; shift 2;;
			-n) P_uname="$2"; shift 2;;
			--) break;;
			*) Help; exit 0;;
		esac
	done
}


#---------------Target user -------------------------------------------#

ParseCommandLineOptions "$@"

if [[ "$P_uname" =~ ^[a-zA-Z\ ]+$ ]]; then
	username="$P_uname"
elif [[ "$P_uid" =~ ^[0-9]+$ ]]; then
	userid="$P_uid"
	username="$( grep "$userid" /etc/passwd  )"
	username="${username%%:*}"
else
	Help
	exit 1
fi

#--------------- delete user from sudo --------------------------------#

gpasswd -d "$username" sudo

#-------------- set sudo execptions for user --------------------------#

printf "%s\n" "$username ALL=(root) PASSWD: $( command -v nethogs ) *" > /etc/sudoers.d/nethogs \
&& chmod 440 /etc/sudoers.d/nethogs


nmap_path=$(command -v nmap) || exit 1
cat > /etc/sudoers.d/nmap <<EOF
Cmnd_Alias NMAP_COMMON = \
	$nmap_path ^(((-sL|-sn|-sS|-sT|-sU|-O|-Pn|-n|-F|-v{1,3}|--open|--reason|--traceroute|-T[0-5]|--osscan-limit|--osscan-guess|-p-|-p [0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*|--top-ports [1-9][0-9]{0,4}|-o(N|X|G) -)) )*((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(/([0-9]|[12][0-9]|3[0-2]))?( ((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(/([0-9]|[12][0-9]|3[0-2]))?)*$, \
    $nmap_path ^--datadir /usr/share/nmap -sV (((-sS|-sT|-sU|-O|-Pn|-n|-F|-v{1,3}|--open|--reason|--traceroute|-T[0-5]|--version-light|--version-all|--osscan-limit|--osscan-guess|-p-|-p [0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*|--top-ports [1-9][0-9]{0,4}|-o(N|X|G) -)) )*((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(/([0-9]|[12][0-9]|3[0-2]))?( ((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(/([0-9]|[12][0-9]|3[0-2]))?)*$

$username ALL=(root) PASSWD: NOSETENV: NMAP_COMMON
EOF
chmod 440 /etc/sudoers.d/nmap


systemctl_path="$( command -v systemctl )"
cat > /etc/sudoers.d/service-restarts <<EOF
Cmnd_Alias SERVICE_RESTARTS = \
    $systemctl_path restart clamav-daemon.service, \
    $systemctl_path restart NetworkManager.service, \
    $systemctl_path restart libvirtd.service

$username ALL=(root) PASSWD: SERVICE_RESTARTS
EOF

#----------------------------------------------------------------------#
